### ISSUE TITLE
About 0_connectomes_SC_FC_schaefer-100.mat

### ISSUE THREAD

**Issue by komabso** [TardifLab/Weighted-SC-Networks#1]
Hello Mark,

I'd like to compare the SC you shared (Thank you so much!) with the SC I made, do you have information on what each of the 9 cells in 0_connectomes_SC_FC_schaefer-100.mat is? 

For example, the first cell is 'fc', and the fourth cell is 'los'.

Any response will be helpful!

Thanks!
Joseph.

**Comment by MarkNelson86** [comment]
Hi Joseph, this information can be found in the derivative file named "2_weights_SC_FC.mat".

**Comment by komabso** [comment]
Oh, I see! 
Thank you for your answer!

**Comment by komabso** [comment]
Hi @MarkNelson86 ,

I'm sorry to bother you again. I have more questions about your data.
I apologize in advance if they are stupid questions.

1. When I compare the degree centrality of SC of Schaefer-400 and SC of Schaefer-100 with respect to each network weight, even though they are the same network weight (e.g., Schaefer-400: fa and Schaefer-100: fa), they don't look similar. As far as I know, one of more parcellated parcellation in each boundary of Schaefer-100 is Schaefer-400, so I think the result should be similar, but it's not. 

**Is there any difference other than parcellation when making the SCs? Or is this normal?** 

I attached the picture below. The picture above is Schaefer-400, and the picture below is Schaefer-100. It looks different even considering that the color range is different.
![image](https://github.com/TardifLab/Weighted-SC-Networks/assets/83950926/8453d791-e073-46d1-9179-50f9807bc74c)
-> Schaefer-400
![image](https://github.com/TardifLab/Weighted-SC-Networks/assets/83950926/19c6c262-3568-4b27-b008-c17e401ac682)
-> Schaefer-100

2. Your paper says that networks parcellated with Schaefer-400 cortical atlas and 14 subcortical nodes, but if I open the SC, there are more nodes than that. For fc it's 449, the other structural network weights are 450 so **what are 35 and 36 additional nodes? Are they cerebellum? If so, what parcellation did you use?** Also, **why does fc's connectome have one less node than SC of other structural network weights?**

Any reply would be very helpful. Thank you.

Best regards,
Joseph.

**Comment by MarkNelson86** [comment]
Perhaps you are not segmenting the connectomes correctly? In addition to the cortical nodes defined by a given parcellation, each connectome contains both subcortical AND cerebellar nodes, as well as medial wall nodes. For my paper, I retained only the cortical and subcortical nodes. See **conn_cut.m**  

I'd also suggest reading through the [micapipe](https://pubmed.ncbi.nlm.nih.gov/36070839/) and [MICs dataset](https://pubmed.ncbi.nlm.nih.gov/36109562/) publications. This would have answered your question about the node count discrepancies.

**Comment by komabso** [comment]
1) I used the schaefer400 and schaefer100 in the plot_hemisphere function of Brainspace. I need to see what their segmentation is like.

2) I understood what you said after seeing conn_cut.m. I'll read the publications of micapipe and MICs dataset.

Your answer will be a great help. Thank you for your reply despite your busy schedule.

Best regards,
Joseph.

**Comment by MarkNelson86** [comment]
See **plot_conn_surf.m** 

This function plots cortical data on the surface using both brainspace and enigma (brainspace for cortical data and enigma for subcortical)
